- name: "Install Strongswan"
  package:
    name: "{{ item }}"
    update_cache: true
  loop:
    - strongswan
    - charon-systemd
    - strongswan-swanctl
- name: "Deactivate systemd-starter"
  ansible.builtin.systemd:
    name: strongswan-starter
    enabled: false
- name: "Deactivate automatic routes"
  lineinfile:
    path: /etc/strongswan.d/charon.conf
    regexp: "^([ \t]*).*install_routes =.*$"
    line: "\\1install_routes = no"
    backrefs: true
- name: "Add Strongswan config"
  template:
    dest: /etc/swanctl/conf.d/from-ansible.conf
    src: files/swanctl.conf.template
    owner: root
    mode: "0644"
  notify:
    - Restart strongswan
- name: "move strongswan into network-namespace if configured"
  when: "'ipsec_namespace' in vars"
  block:
    - name: create strongswan.service.d directory
      file:
        path: /etc/systemd/system/strongswan.service.d
        state: directory
        owner: root
        group: root
        mode: 0755
    - name: create strongswan.service drop-in
      copy:
        dest: /etc/systemd/system/strongswan.service.d/override.conf
        content: |
          [Service]
          NetworkNamespacePath=/var/run/netns/{{ bgp.netns }}
      notify:
        - Restart strongswan
- name: "start strongswan"
  systemd:
    daemon_reload: true
    name: strongswan
    enabled: true
    state: started
- name: "prepare netns command"
  set_fact:
    netns_command: |
      {{ 'ip netns exec ' + ipsec_namespace if 'ipsec_namespace' in vars else '' }}
- name: "configure networking"
  blockinfile:
    path: /etc/network/interfaces
    block: |
      {% for item in ipsec_peers %}
      # ipsec to {{ item.name }}
      auto ipsec{{ loop.index0 }}
      iface ipsec{{ loop.index0 }} inet manual
        # please note that the "if_id" is the same as the "if_id_*" in swanctl.conf
        pre-up {{ netns_command | trim }} ip link add ipsec{{ loop.index0 }} type xfrm dev lo if_id {{ 158 + loop.index0 }}
        pre-up {{ netns_command | trim }} sysctl net.ipv6.conf.ipsec{{ loop.index0 }}.autoconf=0
        pre-up {{ netns_command | trim }} ip link set up dev ipsec{{ loop.index0 }}
        post-up {{ netns_command | trim }} ip addr add {{ item.ipsec_net }} dev ipsec{{ loop.index0 }}
        {% if 'ipsec_net6' in item %}
        post-up {{ netns_command | trim }} ip -6 addr add {{ item.ipsec_net6 }} dev ipsec{{ loop.index0 }}
        {% endif %}
        {% for route in item.routes %}
        post-up {{ netns_command | trim }} ip route replace {{ route }} via {{ item.ipsec_net | ansible.netcommon.ipaddr('peer') }}
        {% endfor %}
        post-down {{ netns_command | trim }} ip link del ipsec{{ loop.index0 }}
      {% endfor %}
